### ISSUE TITLE
Whats the difference between this and starlette ?!

### ISSUE THREAD

**Issue by manatlan** [kennethreitz/responder#216]
I should be completly dumb ;-) ... sorry

But I can't see the things that "responder" does more than "starlette" ?
What are the added values ?

I really think it should be clarified in the doc ...
All highlighted features comes from starlette, no ?

**Comment by tomchristie** [comment]
(Speaking purely for myself here)

We've both been working away pretty quickly on our own separate projects, so there are some things in Responder that weren't in Starlette at the time. (e.g. GraphQL support, Session support)

There's also a bunch of things that responder does on top:

* Responder gives you content-negotiated requests and responses.
* Responder gives you mutable responses, and a `func(request, response)` API instead of `func(request) -> response`, it also gives you a different class-based style.
* Responder gives you an API where you don't need to import anything, and don't rely on subclassing anywhere. (I think I quite like that, even though it's certainly not what Starlette should do)
* Responder makes some informed choices about what default middleware stack you might want.
* Responder makes some informed choices about what set of packages you might want as part of the framework.

I think there'd be some good mileage to be had in responder perhaps being more starlette-like in some of the internals, but ultimately I guess it's about providing a different developer experience.

**Comment by mmanhertz** [comment]
A favorite feature of mine is also the integrated docstring -> openapi docs support, which I believe is not in starlette.

**Comment by pohlt** [comment]
I'm sure, Kenneth and Tom have discussed this question before: Wouldn't it be more efficient if the two developers would join forces and work on one framework? Are the two use cases for starlette and responders really that incompatible?
Anyway, thanks to both for their great work!
