### ISSUE TITLE
Need more example code

### ISSUE THREAD

**Issue by drax2gma** [kennethreitz/responder#232]
Hello,

is it possible to get more examples for using awesome responder? Maybe best practices for converting existing Flask often used method calls and alike. Thanks!

Mark

**Comment by Serkan-devel** [comment]
I'd be interested in a example file-structure of a project using this framework

**Comment by mmanhertz** [comment]
Here's an example for how we are currently structuring a small service (to be deployed as a docker container to kubernetes) were I work:

```
<project_root>/
├── service/
│   ├── apis/
│   │     ├── __init__.py
│   │     ├── <resource1>.py
│   │     └── <resource2>.py
│   ├── models/
│   │     ├── __init__.py
│   │     ├── <resource1>.py
│   │     └── <resource2>.py
│   └── app.py
├── test/
│   ├── __init__.py
│   ├── <resource1>.py
│   └── <resource2>.py
├── .env
├── .gitignore
├── Dockerfile
├── k8s-deployment.yaml
├── Pipfile
├── Pipfile.lock
└── README.md
```

The `<resourceX>.py` files in `service/apis` contain the [class based views](https://python-responder.org/en/latest/tour.html#class-based-views) implementing the different GET, POST, PUT, etc... endpoints for the different resources the service is concerned with. 

The corresponding files in `service/models` contain the [marshmallow schemas](https://python-responder.org/en/latest/tour.html#openapi-schema-support) to go with that.

In `service/app.py` this is then tied together like this:
```python
import responder

from service.apis.resource1 import Resource1View
from service.apis.resource2 import Resource2View
from service.models.resource1 import Resource1Schema
from service.models.resource2 import Resource2Schema

api = responder.API(
    title="My Service",
    version="1.0",
    openapi="3.0.0",
    docs_route='/docs',
)

api.add_schema('Resource1', Resource1Schema)
api.add_schema('Resource2', Resource2Schema)
api.add_route('/route/to/resource1', Resource1View)
api.add_route('/route/to/resource2', Resource2View)

if __name__ == "__main__":
    api.run(port=5000, address='0.0.0.0')
```

This works for us. YMMV. Feel free to use this however you like. I'd also appreciate feedback, if you think this doesn't make sense or could be improved.

**Comment by kennethreitz** [comment]
Makes perfect sense to me!

**Comment by Serkan-devel** [comment]
@mmanhertz thank you for the example. I might orientate from it on this project https://github.com/Serkan-devel/Nebelscheibe but there's nothing there yet

**Comment by here0to0learn** [comment]
@mmanhertz how would you import the schemas for the swagger documentation in the above example? 
When all the endpoints are in one `views.py`, adding a decorator before the route adds it to the swagger doc as well.

**Comment by here0to0learn** [comment]
Right. I tried your example with the following contents of respective files (Assuming the schema is correctly setup):

**Content of apis.resource1**
```
class Resource1View:
    def on_request(req, resp):
        resp.media({"hello": "world"})
```
Maybe i am missing something here, but this does not get picked up by the swagger docs. I wonder if the names matter and everything should match everywhere?

When all the endpoints are in single views.py, the endpoint would look like following:\
```
class Resource1View:
    **@app.route('/resource1')**
    def on_request(req, resp):
        resp.media({"hello": "world"})
```
and this would let swagger pickup the endpoint to display properly.

**Comment by mmanhertz** [comment]
@here0to0learn I think you are missing the docstring, as in [the example from the responder docs](https://python-responder.org/en/latest/tour.html#openapi-schema-support).
Here's how we do it in our project:
```python
@app.route('/path/to/resource1')
class Resource1View:
    """An endpoint for resource 1
    ---
    get:
        description: Get a random pet
        responses:
            200:
                description: Success
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Resource1'
    """
    def on_request(req, resp):
        resp.media(<Actually return a JSON dump of resource1 here>)
```

Any valid OpenAPI schema in the docstring will be added to the swagger UI as far as I can tell.

**Comment by here0to0learn** [comment]
More over, the endpoints themselves registering with swagger docs does not have anything to do with the schema itself. The docstring should be enough to register an endpoint to the swagger docs (yaml file basically). E.g. the above content i posted in `app.resource1` with the docstring should show up as an endpoint in swagger docs but doesn't.

**Comment by mmanhertz** [comment]
Strange, it does work flawlessly for us. The one difference I can see: we are actually using the `on_get` and `on_post` functions instead of `on_request`... don't know if that's relevant, though.

I will try to hack together a quick minimal working example repo tonight, if I have the time.

**Comment by here0to0learn** [comment]
Tried that as well. It did not work :(

**Comment by Saravana9210** [comment]
Can someone give an example how do we use on_get, on_post and on_put with responder?

I'm trying to use same route for 2 diff methods GET and POST, but I get following error (looks like I can not use same route for diff routes:

***************************
Traceback (most recent call last):
  File "api.py", line 23, in <module>
    @api.route("/{anything}")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/responder/api.py", line 502, in decorator
    self.add_route(route, f, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/responder/api.py", line 400, in add_route
    assert route not in self.routes
AssertionError
************************

Below is the sample code I'm trying:

@api.route("/{anything}")   ==> intention is that GET request should go here
def mock_service(req, res, *, anything):
      res.text = "GET request successfully executed"

@api.route("/{anything}")  ==> intention is that POST request should go here
async def on_post(self, req, resp, *, anything):
      data = await req.media()
      // do something with data

**Comment by mmanhertz** [comment]
@Saravana9210 

You need to put the methods in a class and put the route decorator on that class, something like this:

```python
@api.route("/{anything}")
class AnyApi:
    def mock_service(req, res, *, anything):
        res.text = "GET request successfully executed"

    async def on_post(self, req, resp, *, anything):
        data = await req.media()
        // do something with data
```

PS: You can format your code examples nicely by enclosing them in triple back-ticks ```

**Comment by Serkan-devel** [comment]
How does one inplement authentication without mounting a flask app?

**Comment by iancleary** [comment]
@Serkan-devel Open to suggestions from the community here on recommended ways.

I think you have several options (note using an HTTPS connection when outside of an isolated development environment):

- Basic HTTP headers per [HTTP Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization)
~~~~
req.headers["authorization"] # reverse the base64 encoding and check against your system
~~~~

- HTTP Headers with custom parameters (username and password)
~~~~
req.headers["username"]
req.headers["password"]
~~~~

Personally, I'm using how [on_request is called before all other on_{method}s ](https://github.com/kennethreitz/responder/blob/master/responder/api.py#L370-L393) and class based views to check headers (application type, credentials, etc.) for my use case.  The general organization of the class is like the above comments and examples in the documentation.  I'm inheriting from a base class that handles the header checks and authorization, so that all my defined routes execute the base classes on_request to handle authorization,etc.

@Saravana9210 (note the example linked in the next paragraph includes the custom params for authorization as stated above, but is another class based example. The difference between @mmanhertz example is that "on_request" is implemented as well (as that is called before all methods, if they are defined in the class).

An example of the custom parameter option and a base_class for an api service in one of my projects is here: [base_service.py](https://github.com/iancleary/ordines/blob/07dab2761fc90558eca0731ee429eb18c5cac168/src/service/common/base_service.py#L123-L159). 

Notes: 
- the project is currently being developed, but the link is some example code to potentially answer your question (and have no dependency on Flask).
- Flask is in the requirements.txt, but that is not a dependency for the linked example code. It is just a preliminary design choice that that I'm choosing to mount a Flask app in my project to have Responder just be an API service (to take advantage of some of the background task features

p.s. Four ~'s also works for formatting code blocks

**Comment by taylorperkins** [comment]
This thread has been very helpful in deciding how to architect apps at a larger scale! Thanks for the examples :)

**Comment by tatianajiselle** [comment]
can someone please clarify for me the difference between api.route() and api.add_route()... ive been working on splitting a project structure with the main in an app.py and routes located in service files. in order to initialize these existing api.route() would i need to use api.add_route in the app.py? 

thanks in advance.

**Comment by knoguchi** [comment]
I just started working on Blueprint for Responder that is similar to Flask Blueprint. 

The main
```
import responder

from bp1 import simple_page

api = responder.API(debug=True)
api.register_blueprint(simple_page, url_prefix='/pages')

if __name__ == '__main__':
    api.run()
```

The blueprint 

```
from responder.blueprints import Blueprint

simple_page = Blueprint('simple_page', __name__, template_folder='templates')

@simple_page.route("/{greeting}")
async def greet_world(req, resp, *, greeting):
    resp.text = f"{greeting}, world!"
```

it works like this
```
$ curl http://127.0.0.1:5042/pages/hello
hello, world!
```
