### ISSUE TITLE
Support newer versions of starlette and/or restrict the installed version in setup.py

### ISSUE THREAD

**Issue by alexwlchan** [kennethreitz/responder#266]
I just installed the latest version of responder from PyPI, which brings in the latest version of starlette. Specifically:

* responder 1.1.2
* starlette 0.9.9

If I run the quick start example from the docs, I get a ModuleNotFoundError from inside starlette:

```python
#!/usr/bin/env python
# -*- encoding: utf-8

import responder

api = responder.API()

@api.route("/{greeting}")
async def greet_world(req, resp, *, greeting):
    resp.text = f"{greeting}, world!"

if __name__ == '__main__':
    api.run()
```

```
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    import responder
  File "/Users/alexwlchan/.virtualenvs/image-board/lib/python3.6/site-packages/responder/__init__.py", line 1, in <module>
    from .core import *
  File "/Users/alexwlchan/.virtualenvs/image-board/lib/python3.6/site-packages/responder/core.py", line 1, in <module>
    from .api import API
  File "/Users/alexwlchan/.virtualenvs/image-board/lib/python3.6/site-packages/responder/api.py", line 17, in <module>
    from starlette.lifespan import LifespanHandler
ModuleNotFoundError: No module named 'starlette.lifespan'
```

Trying different versions of starlette, it looks like this broke in starlette 0.9.0.

responder should either support the latest version of starlette, or add a dependency bound so I can't install into a broken state.

**Comment by nick-lehmann** [comment]
The issue is caused because `starlette.lifespan` is now a middleware. While you did not specify how you installed `starlette`, I guess you installed it using plain `pip`. When installing `pipenv` using pipenv, `starlette` is pinned to `0.8`, as shown by `pipenv graph`.

```
>>> pipenv graph
responder==1.1.2
  [...]
  - rfc3986 [required: Any, installed: 1.2.0]
  - starlette [required: Any, installed: 0.8.0]
  - uvicorn [required: Any, installed: 0.3.23]
    - click [required: Any, installed: 7.0]
  [...]
```

I also created a virtualenv the traditional way and installed `starlette` with plan `pip` and get the same result as you

```
>>> virtualenv -p python3.6 responder_env
>>> pip install responder
>>> pip freeze
[...]
six==1.12.0
starlette==0.9.9
urllib3==1.24.1
uvicorn==0.3.23
[...]
```

While you are absolutely right that installing via plain pip should work, please note that the [officially recommended way](https://python-responder.org/en/latest/) to install `starlette` is using `pipenv`.

**Comment by nick-lehmann** [comment]
@tym-xqo Yes, you're right, my mistake. I did remove the `pipenv` before but had `starlette==0.8` installed earlier. Not sure why it reused this version, but now in a different directory I also get the latest version.

The issues you described is also something a experienced and described [here](https://github.com/kennethreitz/responder/issues/255) when a contributer recommended trying out installing the very latest version because the latest release has a problem as a result of the moved `starlette.lifespan` module.

**Comment by sepulworld** [comment]
Verified `pipenv uninstall starlette; pipenv install "starlette<0.9"` is good workaround for now.
