### ISSUE TITLE
API documentation generation

### ISSUE THREAD

**Issue by momothereal** [kennethreitz/responder#32]
Having a built-in REST API documentation builder could be a nice-to-have feature, although I acknowledge it might be out of scope (maybe as some sort of add-on?). 

Some may be familiar with documentation explorers like [Swagger UI](https://swagger.io/tools/swagger-ui/), which uses the OpenAPI spec. Is there any interest in making something like this a built-in feature?

**Comment by tomchristie** [comment]
Precursor: Generate OpenAPI schemas. I'd suggest we just do that directly (plain old dicts etc... rather than relying on any library. The only place where we *might* want to expand on that would be the types. (Eg. `apistar` has a type system that is designed to map nicely onto JSONSchema which is useful here)

I'd suggest using apistar's schema validation to make sure we're doing so correctly... https://docs.apistar.com/schema-validation/

Once we're generating OpenAPI schemas then we can take our pick of API docs generators. We could lean on `apistar.docs(schema)` here if wanted - https://docs.apistar.com/api-documentation/

**Comment by kennethreitz** [comment]
this is now built
