### ISSUE TITLE
Wrong python version classifiers ?

### ISSUE THREAD

**Issue by waghanza** [kennethreitz/responder#368]
Hi @kenneth-reitz ,

I can see that python version required on `Pipenv` is **3.7**
https://github.com/kennethreitz/responder/blob/6dbbad158a2e2b24a034856c7801f7f6408bdc3d/Pipfile#L20

However, classifiers (in `setup.py`) tells us that `responder` could be used in either **3.6**  or **3.7**

What is the version in `Pipfile` for ?

Regards,

**Comment by timofurrer** [comment]
It's used to tell `pipenv` which version of Python the dependencies were / will be ocked with - so, the created virtualenv uses that version of Python.

However, since `responder` is a framework and can be used with multiple version of Python feel free to change that `python_version` for you to Python 3.6 when developing `responder`. It doesn't affect the deployment though.

**Comment by waghanza** [comment]
@timofurrer If I understand, there is not reason to keep this in `Pipfile` right ?

in fact I've also noticed, that `python` `3.7` was not **tested** in `CI`
