### ISSUE TITLE
Support startup, shutdown, and timer events.

### ISSUE THREAD

**Issue by tomchristie** [kennethreitz/responder#58]
ASGI includes a `lifespan` messaging channel, which provides startup and shutdown events.
This also means there's a managed context within which we can hook timer events.

Interfaces for this might look something like...

```python
@app.on_event('startup')
async def startup():
    ...
```

```python
@app.on_event('tick', seconds=10)
async def do_stuff():
    ...
```

```python
@app.on_event('shutdown')
async def startup():
    ...
```

These would be a nice easy win that ASGI gives us which WSGI isn't able to.

Starlette currently supports startup and shutdown events, so that's a good first place to look for implementation... https://www.starlette.io/events/

**Comment by kennethreitz** [comment]
I'm not convinced this is a good idea, at this time.

**Comment by pbsds** [comment]
Please don't close this yet. The startup one is kinda essential to be honest if you want to perform async setup, like creating a dbpool:

This is due to the event loop not being created before after you've run api.run(), which then blocks.
You could pass your own loop instance as an option into api.run() which would then be passed into uvicorn to use, but it isn't pretty nor pythonic.
